#FILENAME: constatnts.py
#PURPOSE:  holds all of the information for our servo and motor positions and sensor numbers

ARM = 0
ARM_START = 1950
ARM_BOTGUY = 1230 #LOWER NUMBERS = HIGHER ARM
ARM_LAZY = 1538
ARM_DOWN = 2000
ARM_UP = 1400

CLAW = 3
CLAW_CLOSED = 1100
CLAW_OPEN = 1900
  
LINE_PORT = 0
THRESH = 3700  #THIS MIGHT NEED TO BE ADJUSTED AT COMP